c_name_dic.Gallopline=Gallopline
c_name_dic.易达优宁波 EPS NB=Ydnb
c_name_dic.Yoka=Yk
c_name_dic.天图 MTLI=TT
c_name_dic.美设 Amass=MS
c_name_dic.德速 Deksu=Ds
c_name_dic.DH SC=DH
c_name_dic.易达优 EPS=YD
c_name_dic.美迈 Miracle Miles=MM
c_name_dic.大M FBA=大M
c_name_dic.~$大M FBA=大M
c_name_dic.~$Yoka=Yk
c_name_dic.~$Gallopline=Gallopline
c_name_dic.~$迅途 XunTu=迅途 XunTu
c_name_dic.迅途 XunTu=迅途 XunTu
c_name_dic.米娅 Mia=米娅 Mia

DEST_LIST=YYZ3,YYZ4,YOO1,XYY1,YHM1,YYZ9,YYZ7,YXU1,YOW1,YOW3,YGK1,私人地址,YYZ1,YYC4/6,YEG1/2,YVR3/4,YEG1,YVR4,YYC4

CARTON_KEYWORDS=ctn,ctns,carton,cartons,no of carton,total ctn,箱数,箱,数量,CTNS,件数,pkgs,发货数量,箱数(ctns),箱数(paks),包装件数


CBM_KEYWORDS=cbm,cmb,volume,体积,总体积,totalvolume,Kos.\nMeasurement\n体积,方数,入库体积,体积(CBM),total volumn(cbm),VOL,MEASUREMENT,求和项:箱规立方,总体积 CBM


WEIGHT_KEYWORDS=weight,kgs,kg,重量,重量KG,G.W.(毛重),实重,实际重量,毛重（KGS),毛重,货物重量


NO_NEED_KEYWORDS= 序号,战略客户标记,派送邮编,柜号,是否FBA,派送方式,渠道名,货物名称,PLTS,渠道,装柜顺序,尾程派送方式,集装箱号（整箱必填）,货物是否已打托,目的国,货物名称,单号,品名,中文品名,英文品名



header_row=0